<?php
/**
 * UserApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MT4 microservice
 *
 * Mt4 microservice. Call /init/ to get token, which is required in other methods.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * UserApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UserApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for 5069Get
     *
     * Get user margin.
     *
     */
    public function test5069Get()
    {
    }

    /**
     * Test case for userAddPost
     *
     * Create user.
     *
     */
    public function testUserAddPost()
    {
    }

    /**
     * Test case for userByUserLoginDelete
     *
     * Delete user.
     *
     */
    public function testUserByUserLoginDelete()
    {
    }

    /**
     * Test case for userByUserLoginGet
     *
     * Get user by user login.
     *
     */
    public function testUserByUserLoginGet()
    {
    }

    /**
     * Test case for userDepositPost
     *
     * Deposit account.
     *
     */
    public function testUserDepositPost()
    {
    }

    /**
     * Test case for userResetPwdPost
     *
     * Reset password.
     *
     */
    public function testUserResetPwdPost()
    {
    }

    /**
     * Test case for userUpdatePost
     *
     * Update user.
     *
     */
    public function testUserUpdatePost()
    {
    }

    /**
     * Test case for userWithdrawPost
     *
     * Withdraw account.
     *
     */
    public function testUserWithdrawPost()
    {
    }
}
